# Site settings
title: Mark Fischer
email: flyingfisch@toppagedesign.com
description: >
  My personal blog where I post about programming as well as other topics.
baseurl: ""
url: "http://flyingfisch.github.io"
twitter_username: flyingfisch_
github_username:  flyingfisch

# Build settings
markdown: KramdownPygments

kramdown:
    auto_ids: true

highlighter: true
paginate: 3

# Default YAML Front Matter
defaults:
  -
    scope:
        path: "" # ever little thang
    values:
        author: Mark Fischer, Jr.

# gems
gems: [jekyll_figure]

figures:
    dir: /assets/figures
    enumerate: true

